// test reducer constants
export const TESTS_FETCH_DATA_REQUEST = "TESTS_FETCH_DATA_REQUEST";
export const TESTS_FETCH_DATA_SUCCESS = "TESTS_FETCH_DATA_SUCCESS";
export const TESTS_FETCH_DATA_FAILURE = "TESTS_FETCH_DATA_FAILURE";
export const TESTS_SEND_TEST_ANSWER = "TESTS_SEND_TEST_ANSWER";
